/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppMemoryRouteImport } from './routes/_app.memory'
import { Route as AppRemindersRouteImport } from './routes/_app.reminders'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSettingsProfileRouteImport } from './routes/_app.settings.profile'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/design-system': typeof DesignSystemRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/chat': typeof AppChatRoute
  '/memory': typeof AppMemoryRoute
  '/reminders': typeof AppRemindersRoute
  '/tasks': typeof AppTasksRoute
  '/settings/profile': typeof AppSettingsProfileRoute
}
export interface FileRoutesByTo {
  '/design-system': typeof DesignSystemRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/chat': typeof AppChatRoute
  '/memory': typeof AppMemoryRoute
  '/reminders': typeof AppRemindersRoute
  '/tasks': typeof AppTasksRoute
  '/': typeof AppIndexRoute
  '/settings/profile': typeof AppSettingsProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/memory': typeof AppMemoryRoute
  '/_app/reminders': typeof AppRemindersRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/chat'
    | '/memory'
    | '/reminders'
    | '/tasks'
    | '/settings/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/design-system'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/chat'
    | '/memory'
    | '/reminders'
    | '/tasks'
    | '/'
    | '/settings/profile'
  id:
    | '__root__'
    | '/_app'
    | '/design-system'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/_app/chat'
    | '/_app/memory'
    | '/_app/reminders'
    | '/_app/tasks'
    | '/_app/'
    | '/_app/settings/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory': {
      id: '/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reminders': {
      id: '/_app/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
